name: Manual release process

on:
  release:
    types:
      - published
      - prereleased

permissions:
  contents: write

jobs:
  build:
    name: Build and upload module
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}
      upload_url: ${{ github.event.release.upload_url }}
      versiontag: ${{ github.event.release.tag_name }}

    steps:

    - name: Set Asset Name
      id: set-asset-name
      run: |
          echo "zipfilename=TameMyCerts_community_${{ github.event.release.tag_name }}.zip" >> $GITHUB_ENV

    - name: Trigger target workflow
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/uploadreleasefile.yml/dispatches \
        -d '{"ref":"main","inputs":{"upload_url":"${{ env.upload_url }}","zipfilename":"${{ env.zipfilename }}","versiontag":"weekly-build"}}'
      env:
        GH_TOKEN: ${{ github.token }}
